version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: blockchain_test
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - ./pg-data:/var/lib/postgresql/data

networks:
  backend:
 
volumes:
  pg-data: {}
